# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.SearchTab = QtWidgets.QWidget()
        self.SearchTab.setObjectName("SearchTab")
        self.searchLineEdit = QtWidgets.QLineEdit(self.SearchTab)
        self.searchLineEdit.setGeometry(QtCore.QRect(0, 10, 671, 20))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchButton = QtWidgets.QPushButton(self.SearchTab)
        self.searchButton.setGeometry(QtCore.QRect(690, 10, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.searchTableView = QtWidgets.QTableView(self.SearchTab)
        self.searchTableView.setGeometry(QtCore.QRect(0, 40, 781, 451))
        self.searchTableView.setObjectName("searchTableView")
        self.tabWidget.addTab(self.SearchTab, "")
        self.UserTab = QtWidgets.QWidget()
        self.UserTab.setObjectName("UserTab")
        self.formLayoutWidget = QtWidgets.QWidget(self.UserTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 751, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.usernamelabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setObjectName("usernamelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernamelabel)
        self.username = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setText("")
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.UserTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 751, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playlistcomboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.playlistcomboBox.setObjectName("playlistcomboBox")
        self.verticalLayout_2.addWidget(self.playlistcomboBox)
        self.playlistTableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.playlistTableView.setObjectName("playlistTableView")
        self.verticalLayout_2.addWidget(self.playlistTableView)
        self.tabWidget.addTab(self.UserTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.gridLayout.addWidget(self.previousButton, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.playpauseButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.playpauseButton.setFont(font)
        self.playpauseButton.setObjectName("playpauseButton")
        self.gridLayout.addWidget(self.playpauseButton, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.elapsedTimeSlider = QtWidgets.QSlider(self.centralwidget)
        self.elapsedTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.elapsedTimeSlider.setObjectName("elapsedTimeSlider")
        self.verticalLayout.addWidget(self.elapsedTimeSlider)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SearchTab), _translate("MainWindow", "Search"))
        self.usernamelabel.setText(_translate("MainWindow", "Username:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.UserTab), _translate("MainWindow", "User"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.playpauseButton.setText(_translate("MainWindow", "Play/Pause"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
